import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="min-h-screen flex flex-col">
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Navbar />
            <main className="flex-grow grid grid-cols-1 lg:grid-cols-10 gap-6 py-8 max-w-7xl mx-auto px-4">
              {/* Sidebar for larger screens */}
              <div className="hidden lg:block lg:col-span-3">
                <Sidebar />
              </div>

              {/* Main content */}
              <div className="lg:col-span-7">{children}</div>
            </main>
            <Toaster />
          </ThemeProvider>
         
        <footer className="w-full flex flex-col items-center justify-center mt-auto py-4">
      <p>&copy; 2025 All Rights Reserved.</p>
      <a
         
        href="https://github.com/kingCoders60"
        className="text-blue-500 underline fixed align:right bottom-4 right-4 animate-pulse"
        target="_blank"
        rel="noopener noreferrer"
      >
        <img src="/github.png" alt="GitHub Icon" width="40" height="40"/> 
      </a>
    </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
